/*
 * GoatChat API
 * server API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConversationDisplayDTO
 */
public class ConversationDisplayDTOTest {
    private final ConversationDisplayDTO model = new ConversationDisplayDTO();

    /**
     * Model tests for ConversationDisplayDTO
     */
    @Test
    public void testConversationDisplayDTO() {
        // TODO: test ConversationDisplayDTO
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'picture'
     */
    @Test
    public void pictureTest() {
        // TODO: test picture
    }

    /**
     * Test the property 'lastMessage'
     */
    @Test
    public void lastMessageTest() {
        // TODO: test lastMessage
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'isSeen'
     */
    @Test
    public void isSeenTest() {
        // TODO: test isSeen
    }

    /**
     * Test the property 'isIntern'
     */
    @Test
    public void isInternTest() {
        // TODO: test isIntern
    }

}
